<?php

namespace app\api\controller\v2;


use app\api\libs\Checkdata;
use app\BaseController;
use app\Request;

class Common extends BaseController
{
    use Checkdata {checkTime as checkTimes;}
    //初始方法中进行参数过滤
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //获取参数
        // halt($this->request->has("timestamp"));
        //判断时间戳是否存在
        // var_dump($this->checkTime());exit;
        $this->checkTime();
        $this->checkSign();
    }

    protected function checkTime()
    {
        if (!$this->request->has("timestamp") || intval($this->request->get("timestamp")) <= 1 || strlen($this->request->get("timestamp")) !== 10) {
            // return $this->return_msg("时间戳错误",[],19997,400);
            echo json_encode(['msg' => "时间戳错误", "errorcode" => 19997, "data" => []]);
            exit;
        }

        if (abs(time() - intval($this->request->get("timestamp"))) > 60) {
            echo json_encode(['msg' => "请求超时", "errorcode" => 19997, "data" => [],"test"=>"测试数据"]);
            exit;
        }
    }
}
